export const CUSTOMER_STATUSES = ['Active', 'On hold'] as const
export type CustomerStatus = (typeof CUSTOMER_STATUSES)[number]

export interface Customer {
  id: string
  name: string
  city: string
  contactName: string
  email: string
  status: CustomerStatus
  joinedAt: string // ISO date, set by the server
}

// id and joinedAt are generated by the server
export type CreateCustomerRequest = Omit<Customer, 'id' | 'joinedAt'>